# Generated by Django 2.2.9 on 2020-02-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
