# Generated by Django 2.2.9 on 2020-02-27 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0006_auto_20200227_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buy.Order'),
        ),
    ]
