# Generated by Django 2.2.10 on 2020-03-01 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0010_auto_20200301_0406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
