# Generated by Django 2.2.10 on 2020-08-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgpa', '0003_course_result_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='course',
        ),
        migrations.RemoveField(
            model_name='result',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
