# Generated by Django 2.2.10 on 2020-08-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgpa', '0006_auto_20200802_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, default='images/cgpa/course_default.jpg', null=True, upload_to='images/cgpa/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cover',
            field=models.ImageField(blank=True, default='images/cgpa/student_default.jpg', null=True, upload_to='images/cgpa/'),
        ),
    ]
