# Generated by Django 2.2.10 on 2020-08-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgpa', '0008_auto_20200802_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
