# Generated by Django 2.2.10 on 2020-08-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgpa', '0011_auto_20200802_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='university',
        ),
    ]
