# Generated by Django 2.2.10 on 2020-08-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgpa', '0012_remove_course_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
