# Generated by Django 2.2.10 on 2020-08-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgpa', '0013_course_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
