# Generated by Django 2.2.10 on 2020-08-02 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cgpa', '0014_auto_20200802_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgpa.Course'),
        ),
    ]
