# Generated by Django 2.2.10 on 2020-03-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
