# Generated by Django 2.2.10 on 2020-07-19 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_info', '0002_auto_20200301_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_info',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
