# Generated by Django 2.2.10 on 2020-07-20 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_info', '0003_book_info_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book_info',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_info.Catagory'),
        ),
        migrations.AlterField(
            model_name='book_info',
            name='cover',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book_info',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book_info',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
