# Generated by Django 2.2.10 on 2020-07-27 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_info', '0004_auto_20200720_0402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name_plural': 'Catagories'},
        ),
        migrations.AlterField(
            model_name='book_info',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_infos', to='book_info.Catagory'),
        ),
    ]
