# Generated by Django 2.2.10 on 2020-07-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_info', '0005_auto_20200727_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_info',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
